title: Mikhail Ivanov
logo: /assets/image/businessphoto.jpg
description: |
  ğŸ“ (832) 738-8240<br>
  ğŸ“§ <a href="mailto:mishaivanov494@yahoo.com">mishaivanov494@yahoo.com</a><br>
  ğŸ“ 16065 Dayton Ave N, Shoreline, WA, 98133<br>
  ğŸŒ <a href="https://www.linkedin.com/in/mvivanov494" target="_blank">LinkedIn</a>
  ğŸŒ <a href="https://github.com/mvivanov494/PortfolioProjects" target="_blank">GitHub</a>
# show_downloads: true
theme: jekyll-theme-minimal
google_analytics: G-HT3YSTSB4F
