title: Mikhail Ivanov
logo: /assets/image/businessphoto.jpg
description: |
  ğŸ“ (832) 738-8240  
  ğŸ“ 16065 Dayton Ave N, Shoreline, WA, 98133  
  ğŸŒ [LinkedIn](https://www.linkedin.com/in/mvivanov494) Â· [GitHub](https://github.com/mvivanov494/PortfolioProjects) Â· ğŸ“§ mishaivanov494@yahoo.com
# show_downloads: true
theme: jekyll-theme-minimal
