title: Mikhail Ivanov
logo: /assets/image/businessphoto.jpg
description: |
  ğŸ“ (832) 738-8240  
  ğŸ“§ mishaivanov494@yahoo.com
  ğŸ“ 16065 Dayton Ave N, Shoreline, WA, 98133  
  ğŸŒ <www.linkedin.com/in/mvivanov494> Â·
  ğŸŒ <github.com/mvivanov494/PortfolioProjects>
# show_downloads: true
theme: jekyll-theme-minimal
